// <auto-generated />
using System;
using Hamper.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamper.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HamperDbContext))]
    partial class HamperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Hamper.Api.Features.History.ArchivedShop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanLengthDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt");

                    b.ToTable("archived_shops", (string)null);
                });

            modelBuilder.Entity("Hamper.Api.Features.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Revision");

                    b.ToTable("items", null, t =>
                        {
                            t.HasCheckConstraint("CK_items_name", "length(\"Name\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_items_size", "\"Size\" IS NULL OR length(\"Size\") <= 100");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Revision");

                    b.ToTable("meals", null, t =>
                        {
                            t.HasCheckConstraint("CK_meals_name", "length(\"Name\") BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Meals.MealLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MealId");

                    b.HasIndex("Revision");

                    b.ToTable("meal_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_meal_lines_count", "\"Count\" >= 1");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("Revision");

                    b.ToTable("days", null, t =>
                        {
                            t.HasCheckConstraint("CK_days_position", "\"Position\" >= 0");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.DayLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Revision");

                    b.ToTable("day_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_day_lines_count", "\"Count\" >= 1");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LengthDays")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Revision");

                    b.ToTable("plan", null, t =>
                        {
                            t.HasCheckConstraint("CK_plan_length_days", "\"LengthDays\" BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.WantedLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Weekly")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Revision");

                    b.ToTable("wanted_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_wanted_lines_count", "\"Count\" >= 1");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Shops.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FromPlan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanLengthDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Revision");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Hamper.Api.Features.Shops.ShopLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOverride")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ticked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Revision");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_shop_lines_count", "\"Count\" >= 1");
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Sync.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentRevision = 0L
                        });
                });

            modelBuilder.Entity("Hamper.Api.Features.Meals.MealLine", b =>
                {
                    b.HasOne("Hamper.Api.Features.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hamper.Api.Features.Meals.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.Day", b =>
                {
                    b.HasOne("Hamper.Api.Features.Meals.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.DayLine", b =>
                {
                    b.HasOne("Hamper.Api.Features.Plans.Day", null)
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hamper.Api.Features.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamper.Api.Features.Plans.WantedLine", b =>
                {
                    b.HasOne("Hamper.Api.Features.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hamper.Api.Features.Shops.ShopLine", b =>
                {
                    b.HasOne("Hamper.Api.Features.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hamper.Api.Features.Shops.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
