/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsIndexRouteImport } from './routes/meals.index'
import { Route as MealsMealIdRouteImport } from './routes/meals.$mealId'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as PlanIndexRouteImport } from './routes/plan.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'
import { Route as ShopBreakdownRouteImport } from './routes/shop.breakdown'
import { Route as MoreHistoryIndexRouteImport } from './routes/more.history.index'
import { Route as MoreHistoryArchivedIdRouteImport } from './routes/more.history.$archivedId'
import { Route as MoreItemsIndexRouteImport } from './routes/more.items.index'
import { Route as MoreItemsItemIdRouteImport } from './routes/more.items.$itemId'
import { Route as PlanMealPlannedMealIdRouteImport } from './routes/plan.meal.$plannedMealId'
import { Route as PlanPickPositionRouteImport } from './routes/plan.pick.$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdRoute = MealsMealIdRouteImport.update({
  id: '/meals/$mealId',
  path: '/meals/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/more/',
  path: '/more/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBreakdownRoute = ShopBreakdownRouteImport.update({
  id: '/shop/breakdown',
  path: '/shop/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreHistoryIndexRoute = MoreHistoryIndexRouteImport.update({
  id: '/more/history/',
  path: '/more/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreHistoryArchivedIdRoute = MoreHistoryArchivedIdRouteImport.update({
  id: '/more/history/$archivedId',
  path: '/more/history/$archivedId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreItemsIndexRoute = MoreItemsIndexRouteImport.update({
  id: '/more/items/',
  path: '/more/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreItemsItemIdRoute = MoreItemsItemIdRouteImport.update({
  id: '/more/items/$itemId',
  path: '/more/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMealPlannedMealIdRoute = PlanMealPlannedMealIdRouteImport.update({
  id: '/plan/meal/$plannedMealId',
  path: '/plan/meal/$plannedMealId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPickPositionRoute = PlanPickPositionRouteImport.update({
  id: '/plan/pick/$position',
  path: '/plan/pick/$position',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals/': typeof MealsIndexRoute
  '/more/': typeof MoreIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/more/history/$archivedId': typeof MoreHistoryArchivedIdRoute
  '/more/items/$itemId': typeof MoreItemsItemIdRoute
  '/plan/meal/$plannedMealId': typeof PlanMealPlannedMealIdRoute
  '/plan/pick/$position': typeof PlanPickPositionRoute
  '/more/history/': typeof MoreHistoryIndexRoute
  '/more/items/': typeof MoreItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals': typeof MealsIndexRoute
  '/more': typeof MoreIndexRoute
  '/plan': typeof PlanIndexRoute
  '/shop': typeof ShopIndexRoute
  '/more/history/$archivedId': typeof MoreHistoryArchivedIdRoute
  '/more/items/$itemId': typeof MoreItemsItemIdRoute
  '/plan/meal/$plannedMealId': typeof PlanMealPlannedMealIdRoute
  '/plan/pick/$position': typeof PlanPickPositionRoute
  '/more/history': typeof MoreHistoryIndexRoute
  '/more/items': typeof MoreItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals/': typeof MealsIndexRoute
  '/more/': typeof MoreIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/more/history/$archivedId': typeof MoreHistoryArchivedIdRoute
  '/more/items/$itemId': typeof MoreItemsItemIdRoute
  '/plan/meal/$plannedMealId': typeof PlanMealPlannedMealIdRoute
  '/plan/pick/$position': typeof PlanPickPositionRoute
  '/more/history/': typeof MoreHistoryIndexRoute
  '/more/items/': typeof MoreItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meals/$mealId'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals/'
    | '/more/'
    | '/plan/'
    | '/shop/'
    | '/more/history/$archivedId'
    | '/more/items/$itemId'
    | '/plan/meal/$plannedMealId'
    | '/plan/pick/$position'
    | '/more/history/'
    | '/more/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meals/$mealId'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals'
    | '/more'
    | '/plan'
    | '/shop'
    | '/more/history/$archivedId'
    | '/more/items/$itemId'
    | '/plan/meal/$plannedMealId'
    | '/plan/pick/$position'
    | '/more/history'
    | '/more/items'
  id:
    | '__root__'
    | '/'
    | '/meals/$mealId'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals/'
    | '/more/'
    | '/plan/'
    | '/shop/'
    | '/more/history/$archivedId'
    | '/more/items/$itemId'
    | '/plan/meal/$plannedMealId'
    | '/plan/pick/$position'
    | '/more/history/'
    | '/more/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealsMealIdRoute: typeof MealsMealIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  ShopBreakdownRoute: typeof ShopBreakdownRoute
  MealsIndexRoute: typeof MealsIndexRoute
  MoreIndexRoute: typeof MoreIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  MoreHistoryArchivedIdRoute: typeof MoreHistoryArchivedIdRoute
  MoreItemsItemIdRoute: typeof MoreItemsItemIdRoute
  PlanMealPlannedMealIdRoute: typeof PlanMealPlannedMealIdRoute
  PlanPickPositionRoute: typeof PlanPickPositionRoute
  MoreHistoryIndexRoute: typeof MoreHistoryIndexRoute
  MoreItemsIndexRoute: typeof MoreItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/more'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/breakdown': {
      id: '/shop/breakdown'
      path: '/shop/breakdown'
      fullPath: '/shop/breakdown'
      preLoaderRoute: typeof ShopBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/history/': {
      id: '/more/history/'
      path: '/more/history'
      fullPath: '/more/history/'
      preLoaderRoute: typeof MoreHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/history/$archivedId': {
      id: '/more/history/$archivedId'
      path: '/more/history/$archivedId'
      fullPath: '/more/history/$archivedId'
      preLoaderRoute: typeof MoreHistoryArchivedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/items/': {
      id: '/more/items/'
      path: '/more/items'
      fullPath: '/more/items/'
      preLoaderRoute: typeof MoreItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/items/$itemId': {
      id: '/more/items/$itemId'
      path: '/more/items/$itemId'
      fullPath: '/more/items/$itemId'
      preLoaderRoute: typeof MoreItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/meal/$plannedMealId': {
      id: '/plan/meal/$plannedMealId'
      path: '/plan/meal/$plannedMealId'
      fullPath: '/plan/meal/$plannedMealId'
      preLoaderRoute: typeof PlanMealPlannedMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/pick/$position': {
      id: '/plan/pick/$position'
      path: '/plan/pick/$position'
      fullPath: '/plan/pick/$position'
      preLoaderRoute: typeof PlanPickPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealsMealIdRoute: MealsMealIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  ShopBreakdownRoute: ShopBreakdownRoute,
  MealsIndexRoute: MealsIndexRoute,
  MoreIndexRoute: MoreIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  MoreHistoryArchivedIdRoute: MoreHistoryArchivedIdRoute,
  MoreItemsItemIdRoute: MoreItemsItemIdRoute,
  PlanMealPlannedMealIdRoute: PlanMealPlannedMealIdRoute,
  PlanPickPositionRoute: PlanPickPositionRoute,
  MoreHistoryIndexRoute: MoreHistoryIndexRoute,
  MoreItemsIndexRoute: MoreItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
