/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsIndexRouteImport } from './routes/meals.index'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as PlanIndexRouteImport } from './routes/plan.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'
import { Route as ShopBreakdownRouteImport } from './routes/shop.breakdown'
import { Route as PlanDayPositionRouteImport } from './routes/plan.day.$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/more/',
  path: '/more/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBreakdownRoute = ShopBreakdownRouteImport.update({
  id: '/shop/breakdown',
  path: '/shop/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDayPositionRoute = PlanDayPositionRouteImport.update({
  id: '/plan/day/$position',
  path: '/plan/day/$position',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals/': typeof MealsIndexRoute
  '/more/': typeof MoreIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/plan/day/$position': typeof PlanDayPositionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals': typeof MealsIndexRoute
  '/more': typeof MoreIndexRoute
  '/plan': typeof PlanIndexRoute
  '/shop': typeof ShopIndexRoute
  '/plan/day/$position': typeof PlanDayPositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/shop/breakdown': typeof ShopBreakdownRoute
  '/meals/': typeof MealsIndexRoute
  '/more/': typeof MoreIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/plan/day/$position': typeof PlanDayPositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals/'
    | '/more/'
    | '/plan/'
    | '/shop/'
    | '/plan/day/$position'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals'
    | '/more'
    | '/plan'
    | '/shop'
    | '/plan/day/$position'
  id:
    | '__root__'
    | '/'
    | '/shop/$shopId'
    | '/shop/breakdown'
    | '/meals/'
    | '/more/'
    | '/plan/'
    | '/shop/'
    | '/plan/day/$position'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  ShopBreakdownRoute: typeof ShopBreakdownRoute
  MealsIndexRoute: typeof MealsIndexRoute
  MoreIndexRoute: typeof MoreIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  PlanDayPositionRoute: typeof PlanDayPositionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/more'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/breakdown': {
      id: '/shop/breakdown'
      path: '/shop/breakdown'
      fullPath: '/shop/breakdown'
      preLoaderRoute: typeof ShopBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/day/$position': {
      id: '/plan/day/$position'
      path: '/plan/day/$position'
      fullPath: '/plan/day/$position'
      preLoaderRoute: typeof PlanDayPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  ShopBreakdownRoute: ShopBreakdownRoute,
  MealsIndexRoute: MealsIndexRoute,
  MoreIndexRoute: MoreIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  PlanDayPositionRoute: PlanDayPositionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
